config/routes.rb
Encuentas::Application.routes.draw do

  resources :bunkers

  resources :incidences

  resources :boxes

  resources :polls
  resources :familystructures
  resources :generals
  resources :poll_steps
  devise_for :admins

  devise_for :users
  
  resources :users

  get "home/index"
  

  root :to => 'home#index'
  

end

app/models/box.rb
class Box < ActiveRecord::Base
  attr_accessible :casilla, :diputado_federal_coalicion_cinco, :diputado_federal_coalicion_cuatro, :diputado_federal_coalicion_dos, :diputado_federal_coalicion_tres, :diputado_federal_coalicion_uno, :diputado_federal_movimiento, :diputado_federal_no_registrado, :diputado_federal_nueva_alianza, :diputado_federal_pan, :diputado_federal_prd, :diputado_federal_pri, :diputado_federal_pt, :diputado_federal_total, :diputado_federal_verde, :diputado_federal_votos_nulos, :direccion, :gob_candidatos_no_registrado, :gob_coalicion_cinco, :gob_coalicion_cuatro, :gob_coalicion_dos, :gob_coalicion_tres, :gob_coalicion_uno, :gob_movimiento, :gob_nueva_alianza, :gob_pan, :gob_prd, :gob_pri, :gob_pt, :gob_total, :gob_verde, :gob_votos_nulos, :hora_apertura, :hora_cierre, :id_incidente, :municipio, :pre_candidatos_no_registrado, :pre_coalicion_cinco, :pre_coalicion_cuatro, :pre_coalicion_dos, :pre_coalicion_tres, :pre_coalicion_uno, :pre_movimiento, :pre_nueva_alinza, :pre_pan, :pre_prd, :pre_pri, :pre_pt, :pre_total, :pre_verde, :pre_votos_nulos, :rc_dos, :rc_tres, :rc_uno, :seccion, :distrito, :user_id
  has_many :incidence
  belongs_to :user
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  before_filter :authenticate_user!,  :user_signed_in?

  # GET /boxes
  # GET /boxes.json
  def index
    if current_user.role == "admin"
      @search = Box.search(params[:search])
      @boxes = @search.all
    else
      @search = current_user.boxes.search(params[:search])
      @boxes = @search.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @boxes }
    end
  end

  # GET /boxes/1
  # GET /boxes/1.json
  def show
    @box = Box.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @box }
    end
  end

  # GET /boxes/new
  # GET /boxes/new.json
  def new
    @box = Box.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @box }
    end
  end

  # GET /boxes/1/edit
  def edit
    @box = Box.find(params[:id])
  end

  # POST /boxes
  # POST /boxes.json
  def create
    @box = Box.new(params[:box])

    respond_to do |format|
      if @box.save
        format.html { redirect_to @box, notice: 'Box was successfully created.' }
        format.json { render json: @box, status: :created, location: @box }
      else
        format.html { render action: "new" }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /boxes/1
  # PUT /boxes/1.json
  def update
    @box = Box.find(params[:id])

    respond_to do |format|
      if @box.update_attributes(params[:box])
        format.html { redirect_to @box, notice: 'Box was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boxes/1
  # DELETE /boxes/1.json
  def destroy
    @box = Box.find(params[:id])
    @box.destroy

    respond_to do |format|
      format.html { redirect_to boxes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/views/boxes/_form.html.erb
<%= form_for @box, :html => { :class => 'table' } do |f| %>
<!-- Grupo uno -->
<div class="well">
	<br/>
  <div class="control-group">
    <p class="control-label">Casilla</p>
    <div class="controls">
      
<%= f.text_field :casilla, :class => 'span1' %>
	 Sección
	 <%= f.text_field :seccion, :class => 'span1' %>	
    </div>
  </div>
<% if current_user.role == "admin" %>
  <div class="control-group">
    <p class="control-label">Usuario</p>
    <div class="controls">
        <%= f.collection_select :user_id, User.all, :id, :email %>
    </div>
  </div>
<% end %>

  <div class="control-group">
    <p class="control-label">Hora de Apertura</p>
    <div class="controls">
      <%= f.datetime_select :hora_apertura, :class => 'date_select' %>
    </div>
  </div>
  <div class="control-group">
    <p class="control-label">Hora de Cierre</p>
    <div class="controls">
      <%= f.datetime_select :hora_cierre, :class => 'date_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :direccion, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :direccion, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :municipio, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :municipio, :class => 'text_field' %>
    </div>
  </div>
</div>
<!-- Termina Grupo uno -->

<!-- Acta para Presidente -->
<table>
  <thead>
    <tr>
      <th>Votos para</th>
      <th>PAN</th>
      <th>PRI</th>
      <th>PRD</th>
      <th>PARTIDO VERDE</th>
      <th>PT</th>
      <th>Movimiento Ciudadano</th>
      <th>Nueva Alianza</th>
      <th>Coalición Uno</th>
      <th>Coalición Dos</th>
      <th>Coalición Tres</th>
      <th>Coalición Cuatro</th>
      <th>Coalición Cinco</th>
      <th>Coalición No Registrados</th>
      <th>Votos Nulos</th>
      <th>Total Presidente</th>
    </tr>
  </thead>
  <tbody>
    <tr>
	  <td>Para presidente</td>	
      <td><%= f.text_field :pre_pan, :class => 'span1' %></td>
      <td><%= f.text_field :pre_pri, :class => 'span1' %></td>
      <td><%= f.text_field :pre_prd, :class => 'span1' %></td>
      <td><%= f.text_field :pre_verde, :class => 'span1' %></td>
      <td><%= f.text_field :pre_pt, :class => 'span1' %></td>
      <td><%= f.text_field :pre_movimiento, :class => 'span1' %></td>
      <td> <%= f.text_field :pre_nueva_alinza, :class => 'span1' %></td>
      <td><%= f.text_field :pre_coalicion_uno, :class => 'span1' %></td>
      <td><%= f.text_field :pre_coalicion_dos, :class => 'span1' %></td>
      <td><%= f.text_field :pre_coalicion_tres, :class => 'span1' %></td>
      <td><%= f.text_field :pre_coalicion_cuatro, :class => 'span1' %></td>
      <td><%= f.text_field :pre_coalicion_cinco, :class => 'span1' %></td>
	<td><%= f.text_field :pre_candidatos_no_registrado, :class => 'span1' %></td>
   <td><%= f.text_field :pre_votos_nulos, :class => 'span1' %></td>
   <td><%= f.text_field :pre_total, :class => 'span1' %></td>
    </tr>
  </tbody>
<tbody>
    <tr>
	  <td>Para Diputado Federal</td>	
      <td><%= f.text_field :diputado_federal_pan, :class => 'span1' %></td>
      <td><%= f.text_field :diputado_federal_pri, :class => 'span1' %></td>
      <td><%= f.text_field :diputado_federal_prd, :class => 'span1' %></td>
      <td><%= f.text_field :diputado_federal_verde, :class => 'span1' %></td>
      <td><%= f.text_field :diputado_federal_pt, :class => 'span1' %></td>
      <td><%= f.text_field :diputado_federal_movimiento, :class => 'span1' %></td>
      <td> <%= f.text_field :diputado_federal_nueva_alianza, :class => 'span1' %></td>
      <td><%= f.text_field :diputado_federal_coalicion_uno, :class => 'span1' %></td>
      <td><%= f.text_field :diputado_federal_coalicion_tres, :class => 'span1' %></td>
      <td><%= f.text_field :diputado_federal_coalicion_tres, :class => 'span1' %></td>
      <td><%= f.text_field :diputado_federal_coalicion_cuatro, :class => 'span1' %></td>
      <td><%= f.text_field :diputado_federal_coalicion_cinco, :class => 'span1' %></td>
	<td><%= f.text_field :diputado_federal_no_registrado, :class => 'span1' %></td>
   <td><%= f.text_field :diputado_federal_votos_nulos, :class => 'span1' %></td>
   <td><%= f.text_field :diputado_federal_total, :class => 'span1' %></td>
    </tr>
  </tbody>


<table>
  <thead>
    <tr>
      <th>Votos para</th>
      <th>PAN</th>
      <th>PRI</th>
      <th>PRD</th>
      <th>PARTIDO VERDE</th>
      <th>PT</th>
      <th>Movimiento Ciudadano</th>
      <th>Nueva Alianza</th>
      <th>Coalición Uno</th>
      <th>Coalición Dos</th>
      <th>Candidatos No registrados</th>
      <th>Votos Nulos</th>
      <th>Total</th>
    </tr>
  </thead>
  <tbody>
    <tr>
	  <td>Gobernador</td>	
      <td><%= f.text_field :gob_pan, :class => 'span1' %></td>
      <td><%= f.text_field :gob_pri, :class => 'span1' %></td>
      <td><%= f.text_field :gob_prd, :class => 'span1' %></td>
      <td><%= f.text_field :gob_verde, :class => 'span1' %></td>
      <td><%= f.text_field :gob_pt, :class => 'span1' %></td>
      <td><%= f.text_field :gob_movimiento, :class => 'span1' %></td>
      <td> <%= f.text_field :gob_nueva_alianza, :class => 'span1' %></td>
      <td><%= f.text_field :gob_coalicion_uno, :class => 'span1' %></td>
      <td><%= f.text_field :gob_coalicion_dos, :class => 'span1' %></td>
      <td><%= f.text_field :gob_candidatos_no_registrado, :class => 'span1' %></td>
      <td><%= f.text_field :gob_votos_nulos, :class => 'span1' %></td>
      <td><%= f.text_field :gob_total, :class => 'span1' %></td>
    </tr>
  </tbody>
</table>

<div class="clear"></div>
<table>
  <thead>
    <tr>
      <th>Votos para</th>
      <th>PAN</th>
      <th>PRI</th>
      <th>PRD</th>
      <th>PARTIDO VERDE</th>
      <th>PT</th>
      <th>Movimiento Ciudadano</th>
      <th>Nueva Alianza</th>
      <th>Coalición Uno</th>
      <th>Votos Nulos</th>
    </tr>
  </thead>
  <tbody>
    <tr>
	  <td>Diputados Locales</td>	
      <td><%= f.text_field :diputado_local_pan, :class => 'span1' %></td>
      <td><%= f.text_field :diputado_local_pri, :class => 'span1' %></td>
      <td><%= f.text_field :diputado_local_prd, :class => 'span1' %></td>
      <td><%= f.text_field :diputado_local_pt, :class => 'span1' %></td>
      <td><%= f.text_field :diputado_local_pvem, :class => 'span1' %></td>
      <td><%= f.text_field :diputado_local_movimiento, :class => 'span1' %></td>
      <td> <%= f.text_field :diputado_local_nueva_alianza, :class => 'span1' %></td>
      <td><%= f.text_field :diputado_local_coalicion_uno, :class => 'span1' %></td>
      <td><%= f.text_field :diputado_local_votos_nulos, :class => 'span1' %></td>
    </tr>
  </tbody>
</table>

<div class="clear"></div>
	
<br>
<table>
  <thead>
    <tr>
      <th>Votos para</th>
      <th>PAN</th>
      <th>PRI</th>
      <th>PRD</th>
      <th>PARTIDO VERDE</th>
      <th>PT</th>
      <th>Movimiento Ciudadano</th>
      <th>Nueva Alianza</th>
      <th>Coalición Uno</th>
      <th>Coalición Dos</th>
      <th>Votos Nulos</th>
    </tr>
  </thead>
  <tbody>
    <tr>
	  <td>Alcaldes</td>	
      <td><%= f.text_field :alcalde_pan, :class => 'span1' %></td>
      <td><%= f.text_field :alcalde_pri, :class => 'span1' %></td>
      <td><%= f.text_field :alcalde_prd, :class => 'span1' %></td>
      <td><%= f.text_field :alcalde_pt, :class => 'span1' %></td>
      <td><%= f.text_field :alcalde_pvem, :class => 'span1' %></td>
      <td><%= f.text_field :alcalde_movimiento, :class => 'span1' %></td>
      <td> <%= f.text_field :alcalde_nueva_alianza, :class => 'span1' %></td>
      <td><%= f.text_field :alcalde_coalicion_uno, :class => 'span1' %></td>
      <td><%= f.text_field :alcalde_coalicion_dos, :class => 'span1' %></td>
      <td><%= f.text_field :alcalde_votos_nulos, :class => 'span1' %></td>
    </tr>
  </tbody>
</table>





  <div class="form-actions">
    <%= f.submit "Guardar", :class => 'btn btn-primary' %>
    <%= link_to "Cancelar",
                boxes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/boxes/edit.html.erb
<%- model_class = @box.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "") %></h1>
<%= render :partial => 'form' %>

app/views/boxes/index.html.erb
<table class="well">
<%= form_for @search do |f| %>
  <p>
    <%= f.label :casilla %>
    <%= f.text_field :casilla_contains %>
  </p>
  <p>
  </p>
  <p class="button"><%= f.submit "Buscar", :class=>"btn btn-mini" %></p>
<% end %>
</div>

<%- model_class = Box.new.class -%>

<h1>Casilla </h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:casilla) %></th>
      <th><%= model_class.human_attribute_name(:seccion) %></th>
      <th><%= model_class.human_attribute_name(:hora_apertura) %></th>
      <th><%= model_class.human_attribute_name(:hora_cierre) %></th>
      <th><%= model_class.human_attribute_name(:direccion) %></th>
      <th><%= model_class.human_attribute_name(:municipio) %></th>
      <th><%= model_class.human_attribute_name(:distrito) %></th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @boxes.each do |box| %>
      <tr>
        <td><%= link_to box.id, edit_box_path(box) %></td>
        <td><%= box.casilla %></td>
        <td><%= box.seccion %></td>
        <td><%= box.hora_apertura %></td>
        <td><%= box.hora_cierre %></td>
        <td><%= box.direccion %></td>
        <td><%= box.municipio %></td>
        <td><%= box.distrito %></td>
	
	<% if current_user.role == "admin" %>
          <%= link_to "Editar", edit_box_path(box), :class => 'btn btn-mini' %>
          <%= link_to "Eliminar", box_path(box),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>

	<% end %>				
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Nueva Captura", new_box_path,
            :class => 'btn btn-primary' %>

app/views/boxes/new.html.erb
<%- model_class = @box.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "Casilla") %></h1>
<%= render :partial => 'form' %>

app/views/boxes/show.html.erb
<%- model_class = @box.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:casilla) %>:</strong></dt>
  <dd><%= @box.casilla %></dd>
  <dt><strong><%= model_class.human_attribute_name(:seccion) %>:</strong></dt>
  <dd><%= @box.seccion %></dd>
  <dt><strong><%= model_class.human_attribute_name(:hora_apertura) %>:</strong></dt>
  <dd><%= @box.hora_apertura %></dd>
  <dt><strong><%= model_class.human_attribute_name(:hora_cierre) %>:</strong></dt>
  <dd><%= @box.hora_cierre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:direccion) %>:</strong></dt>
  <dd><%= @box.direccion %></dd>
  <dt><strong><%= model_class.human_attribute_name(:municipio) %>:</strong></dt>
  <dd><%= @box.municipio %></dd>
  <dt><strong><%= model_class.human_attribute_name(:id_incidente) %>:</strong></dt>
  <dd><%= @box.id_incidente %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rc_uno) %>:</strong></dt>
  <dd><%= @box.rc_uno %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rc_dos) %>:</strong></dt>
  <dd><%= @box.rc_dos %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rc_tres) %>:</strong></dt>
  <dd><%= @box.rc_tres %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pre_pan) %>:</strong></dt>
  <dd><%= @box.pre_pan %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pre_pri) %>:</strong></dt>
  <dd><%= @box.pre_pri %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pre_prd) %>:</strong></dt>
  <dd><%= @box.pre_prd %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pre_verde) %>:</strong></dt>
  <dd><%= @box.pre_verde %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pre_pt) %>:</strong></dt>
  <dd><%= @box.pre_pt %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pre_movimiento) %>:</strong></dt>
  <dd><%= @box.pre_movimiento %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pre_nueva_alinza) %>:</strong></dt>
  <dd><%= @box.pre_nueva_alinza %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pre_coalicion_uno) %>:</strong></dt>
  <dd><%= @box.pre_coalicion_uno %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pre_coalicion_dos) %>:</strong></dt>
  <dd><%= @box.pre_coalicion_dos %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pre_coalicion_tres) %>:</strong></dt>
  <dd><%= @box.pre_coalicion_tres %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pre_coalicion_cuatro) %>:</strong></dt>
  <dd><%= @box.pre_coalicion_cuatro %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pre_coalicion_cinco) %>:</strong></dt>
  <dd><%= @box.pre_coalicion_cinco %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pre_candidatos_no_registrado) %>:</strong></dt>
  <dd><%= @box.pre_candidatos_no_registrado %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pre_votos_nulos) %>:</strong></dt>
  <dd><%= @box.pre_votos_nulos %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pre_total) %>:</strong></dt>
  <dd><%= @box.pre_total %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gob_pan) %>:</strong></dt>
  <dd><%= @box.gob_pan %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gob_pri) %>:</strong></dt>
  <dd><%= @box.gob_pri %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gob_prd) %>:</strong></dt>
  <dd><%= @box.gob_prd %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gob_verde) %>:</strong></dt>
  <dd><%= @box.gob_verde %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gob_pt) %>:</strong></dt>
  <dd><%= @box.gob_pt %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gob_movimiento) %>:</strong></dt>
  <dd><%= @box.gob_movimiento %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gob_nueva_alianza) %>:</strong></dt>
  <dd><%= @box.gob_nueva_alianza %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gob_coalicion_uno) %>:</strong></dt>
  <dd><%= @box.gob_coalicion_uno %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gob_coalicion_dos) %>:</strong></dt>
  <dd><%= @box.gob_coalicion_dos %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gob_coalicion_tres) %>:</strong></dt>
  <dd><%= @box.gob_coalicion_tres %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gob_coalicion_cuatro) %>:</strong></dt>
  <dd><%= @box.gob_coalicion_cuatro %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gob_coalicion_cinco) %>:</strong></dt>
  <dd><%= @box.gob_coalicion_cinco %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gob_candidatos_no_registrado) %>:</strong></dt>
  <dd><%= @box.gob_candidatos_no_registrado %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gob_votos_nulos) %>:</strong></dt>
  <dd><%= @box.gob_votos_nulos %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gob_total) %>:</strong></dt>
  <dd><%= @box.gob_total %></dd>
  <dt><strong><%= model_class.human_attribute_name(:diputado_federal_pan) %>:</strong></dt>
  <dd><%= @box.diputado_federal_pan %></dd>
  <dt><strong><%= model_class.human_attribute_name(:diputado_federal_pri) %>:</strong></dt>
  <dd><%= @box.diputado_federal_pri %></dd>
  <dt><strong><%= model_class.human_attribute_name(:diputado_federal_prd) %>:</strong></dt>
  <dd><%= @box.diputado_federal_prd %></dd>
  <dt><strong><%= model_class.human_attribute_name(:diputado_federal_verde) %>:</strong></dt>
  <dd><%= @box.diputado_federal_verde %></dd>
  <dt><strong><%= model_class.human_attribute_name(:diputado_federal_pt) %>:</strong></dt>
  <dd><%= @box.diputado_federal_pt %></dd>
  <dt><strong><%= model_class.human_attribute_name(:diputado_federal_movimiento) %>:</strong></dt>
  <dd><%= @box.diputado_federal_movimiento %></dd>
  <dt><strong><%= model_class.human_attribute_name(:diputado_federal_nueva_alianza) %>:</strong></dt>
  <dd><%= @box.diputado_federal_nueva_alianza %></dd>
  <dt><strong><%= model_class.human_attribute_name(:diputado_federal_coalicion_uno) %>:</strong></dt>
  <dd><%= @box.diputado_federal_coalicion_uno %></dd>
  <dt><strong><%= model_class.human_attribute_name(:diputado_federal_coalicion_dos) %>:</strong></dt>
  <dd><%= @box.diputado_federal_coalicion_dos %></dd>
  <dt><strong><%= model_class.human_attribute_name(:diputado_federal_coalicion_tres) %>:</strong></dt>
  <dd><%= @box.diputado_federal_coalicion_tres %></dd>
  <dt><strong><%= model_class.human_attribute_name(:diputado_federal_coalicion_cuatro) %>:</strong></dt>
  <dd><%= @box.diputado_federal_coalicion_cuatro %></dd>
  <dt><strong><%= model_class.human_attribute_name(:diputado_federal_coalicion_cinco) %>:</strong></dt>
  <dd><%= @box.diputado_federal_coalicion_cinco %></dd>
  <dt><strong><%= model_class.human_attribute_name(:diputado_federal_no_registrado) %>:</strong></dt>
  <dd><%= @box.diputado_federal_no_registrado %></dd>
  <dt><strong><%= model_class.human_attribute_name(:diputado_federal_votos_nulos) %>:</strong></dt>
  <dd><%= @box.diputado_federal_votos_nulos %></dd>
  <dt><strong><%= model_class.human_attribute_name(:diputado_federal_total) %>:</strong></dt>
  <dd><%= @box.diputado_federal_total %></dd>
</dl>

<% if current_user.role == "admin" %>
<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              boxes_path, :class => 'btn'  %>

  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_box_path(@box), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              box_path(@box),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>

</div>

<% end %>