config/routes.rb
Encuentas::Application.routes.draw do

  resources :bunkers

  resources :incidences

  resources :boxes

  resources :polls
  resources :familystructures
  resources :generals
  resources :poll_steps
  devise_for :admins

  devise_for :users
  
  resources :users

  get "home/index"
  

  root :to => 'home#index'
  

end

app/models/bunker.rb
class Bunker < ActiveRecord::Base
  attr_accessible :box_id, :casilla_cinco, :casilla_cuatro, :casilla_diez, :casilla_dos, :casilla_nueve, :casilla_ocho, :casilla_seis, :casilla_siete, :casilla_tres, :casilla_uno, :en_operacion, :en_ruta, :municipio, :nombre, :telefono
end

app/controllers/bunkers_controller.rb
class BunkersController < ApplicationController
  # GET /bunkers
  # GET /bunkers.json
  def index
    @bunkers = Bunker.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bunkers }
    end
  end

  # GET /bunkers/1
  # GET /bunkers/1.json
  def show
    @bunker = Bunker.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bunker }
    end
  end

  # GET /bunkers/new
  # GET /bunkers/new.json
  def new
    @bunker = Bunker.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bunker }
    end
  end

  # GET /bunkers/1/edit
  def edit
    @bunker = Bunker.find(params[:id])
  end

  # POST /bunkers
  # POST /bunkers.json
  def create
    @bunker = Bunker.new(params[:bunker])

    respond_to do |format|
      if @bunker.save
        format.html { redirect_to @bunker, notice: 'Bunker was successfully created.' }
        format.json { render json: @bunker, status: :created, location: @bunker }
      else
        format.html { render action: "new" }
        format.json { render json: @bunker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bunkers/1
  # PUT /bunkers/1.json
  def update
    @bunker = Bunker.find(params[:id])

    respond_to do |format|
      if @bunker.update_attributes(params[:bunker])
        format.html { redirect_to @bunker, notice: 'Bunker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bunker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bunkers/1
  # DELETE /bunkers/1.json
  def destroy
    @bunker = Bunker.find(params[:id])
    @bunker.destroy

    respond_to do |format|
      format.html { redirect_to bunkers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/bunkers_helper.rb
module BunkersHelper
end

app/views/bunkers/_form.html.erb
<%= form_for @bunker, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :municipio, :class => 'control-label' %>
    <div class="controls">

<%= f.select :municipio, [["Abasolo", "Abasolo"], ["Acámbaro", "Acámbaro"], ["Apaseo el Alto", "Apaseo el Alto"], ["Apaseo el Grande", "Apaseo el Grande"], ["Atarjea", "Atarjea"], ["Celaya", "Celaya"], ["Comonfort", "Comonfort"], ["Coroneo", "Coroneo"], ["Cortázar", "Cortázar"], ["Cuerámaro", "Cuerámaro"], ["Doctor Mora", "Doctor Mora"], ["Dolores Hidalgo	", "Dolores Hidalgo"], ["Guanajuato", "Guanajuato"], ["Huanímaro", "Huanímaro"], ["Irapuato", "Irapuato"], ["Jaral del Progreso", "Jaral del Progreso"], ["Jerécuaro", "Jerécuaro"], ["León", "León"], ["Manuel Doblado", "Manuel Doblado"], ["Moroleón", "Moroleón"], ["Ocampo", "Ocampo"], ["Pénjamo", "Pénjamo"], ["Pueblo Nuevo", "Pueblo Nuevo"], ["Purísima del Rincón", "Purísima del Rincón"], ["Romita", "Romita"], ["Salamanca", "Salamanca"], ["Salvatierra", "Salvatierra"], ["San Diego de la Unión", "San Diego de la Unión"], ["San Felipe", "San Felipe"], ["San Francisco del Rincón", "San Francisco del Rincón"], ["San José Iturbide", "San José Iturbide"], ["San Luis de la Paz", "San Luis de la Paz"], ["San Miguel de Allende", "San Miguel de Allende"], ["Santa Catarina", "Santa Catarina"], ["Santa Cruz de Juventino Rosas", "Santa Cruz de Juventino Rosas"], ["Santiago Maravatío", "Santiago Maravatío"], ["Silao", "Silao"], ["Tarandacuao", "Tarandacuao"], ["Tarimoro", "Tarimoro"], ["Tierra Blanca", "Tierra Blanca"], ["Uriangato", "Uriangato"], ["Valle de Santiago", "Valle de Santiago"], ["Victoria", "Victoria"], ["Villagrán", "Villagrán"], ["Xichú", "Xichú"], ["Yuriria", "Yuriria"] ], :class => "number_field" %>

    </div>
  </div>
  <div class="control-group">
    <%= f.label "Bunker en Operación", :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :en_operacion, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "RG's en ruta", :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :en_ruta, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :nombre, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nombre, :class => 'span2' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :casilla_uno, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :casilla_uno, :class => 'span2' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :casilla_dos, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :casilla_dos, :class => 'span2' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :casilla_tres, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :casilla_tres, :class => 'span2' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :casilla_cuatro, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :casilla_cuatro, :class => 'span2' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :casilla_cinco, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :casilla_cinco, :class => 'span2' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :casilla_seis, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :casilla_seis, :class => 'span2' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :casilla_siete, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :casilla_siete, :class => 'span2' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :casilla_ocho, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :casilla_ocho, :class => 'span2' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :casilla_nueve, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :casilla_nueve, :class => 'span2' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :casilla_diez, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :casilla_diez, :class => 'span2' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit "Crear Bunker", :class => 'btn btn-primary' %>
    <%= link_to "Cancelar",
                bunkers_path, :class => 'btn' %>
  </div>
<% end %>

app/views/bunkers/edit.html.erb
<%- model_class = @bunker.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Editar #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bunkers/index.html.erb
<%- model_class = Bunker.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:municipio) %></th>
      <th><%= model_class.human_attribute_name(:en_operacion) %></th>
      <th>RG's en ruta</th>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%= model_class.human_attribute_name(:casilla_uno) %></th>
      <th><%= model_class.human_attribute_name(:casilla_dos) %></th>
      <th><%= model_class.human_attribute_name(:casilla_tres) %></th>
      <th><%= model_class.human_attribute_name(:casilla_cuatro) %></th>
      <th><%= model_class.human_attribute_name(:casilla_cinco) %></th>
      <th><%= model_class.human_attribute_name(:casilla_seis) %></th>
      <th><%= model_class.human_attribute_name(:casilla_siete) %></th>
      <th><%= model_class.human_attribute_name(:casilla_ocho) %></th>
      <th><%= model_class.human_attribute_name(:casilla_nueve) %></th>
      <th><%= model_class.human_attribute_name(:casilla_diez) %></th>
      <th>Creado a las</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @bunkers.each do |bunker| %>
      <tr>
        <td><%= link_to bunker.id, edit_bunker_path(bunker) %></td>
        <td><%= bunker.municipio %></td>
		<% if bunker.en_operacion == true %>
        	<td>Está en Operación</td>	
			<% else %>	
			 	<td>No ha iniciado</td>
		<% end  %>		
		<% if bunker.en_ruta == true %>
        	<td>Esta en la casilla</td>	
			<% else %>
			 	<td>No ha llegado</td>
		<% end  %>
        <td><%= bunker.nombre %></td>
        <td><%= bunker.casilla_uno %></td>
        <td><%= bunker.casilla_dos %></td>
        <td><%= bunker.casilla_tres %></td>
        <td><%= bunker.casilla_cuatro %></td>
        <td><%= bunker.casilla_cinco %></td>
        <td><%= bunker.casilla_seis %></td>
        <td><%= bunker.casilla_siete %></td>
        <td><%= bunker.casilla_ocho %></td>
        <td><%= bunker.casilla_nueve %></td>
        <td><%= bunker.casilla_diez %></td>
        <td><%=l bunker.created_at %></td>
        <td>
          <%= link_to "Editar",
                      edit_bunker_path(bunker), :class => 'btn btn-mini' %>
          <%= link_to "Eliminar",
                      bunker_path(bunker),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Estas seguro?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Nuevo", new_bunker_path, :class => 'btn btn-primary' %>

app/views/bunkers/new.html.erb
<%- model_class = @bunker.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "Nuevo Bunker") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bunkers/show.html.erb
<%- model_class = @bunker.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:municipio) %>:</strong></dt>
  <dd><%= @bunker.municipio %></dd>
  <dt><strong><%= model_class.human_attribute_name(:en_operacion) %>:</strong></dt>
  <dd><%= @bunker.en_operacion %></dd>
  <dt><strong><%= model_class.human_attribute_name(:en_ruta) %>:</strong></dt>
  <dd><%= @bunker.en_ruta %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nombre) %>:</strong></dt>
  <dd><%= @bunker.nombre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:casilla_uno) %>:</strong></dt>
  <dd><%= @bunker.casilla_uno %></dd>
  <dt><strong><%= model_class.human_attribute_name(:casilla_dos) %>:</strong></dt>
  <dd><%= @bunker.casilla_dos %></dd>
  <dt><strong><%= model_class.human_attribute_name(:casilla_tres) %>:</strong></dt>
  <dd><%= @bunker.casilla_tres %></dd>
  <dt><strong><%= model_class.human_attribute_name(:casilla_cuatro) %>:</strong></dt>
  <dd><%= @bunker.casilla_cuatro %></dd>
  <dt><strong><%= model_class.human_attribute_name(:casilla_cinco) %>:</strong></dt>
  <dd><%= @bunker.casilla_cinco %></dd>
  <dt><strong><%= model_class.human_attribute_name(:casilla_seis) %>:</strong></dt>
  <dd><%= @bunker.casilla_seis %></dd>
  <dt><strong><%= model_class.human_attribute_name(:casilla_siete) %>:</strong></dt>
  <dd><%= @bunker.casilla_siete %></dd>
  <dt><strong><%= model_class.human_attribute_name(:casilla_ocho) %>:</strong></dt>
  <dd><%= @bunker.casilla_ocho %></dd>
  <dt><strong><%= model_class.human_attribute_name(:casilla_nueve) %>:</strong></dt>
  <dd><%= @bunker.casilla_nueve %></dd>
  <dt><strong><%= model_class.human_attribute_name(:casilla_diez) %>:</strong></dt>
  <dd><%= @bunker.casilla_diez %></dd>
  <dt><strong><%= model_class.human_attribute_name(:box_id) %>:</strong></dt>
  <dd><%= @bunker.box_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              bunkers_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_bunker_path(@bunker), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              bunker_path(@bunker),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>