config/routes.rb
Encuentas::Application.routes.draw do

  resources :bunkers

  resources :incidences

  resources :boxes

  resources :polls
  resources :familystructures
  resources :generals
  resources :poll_steps
  devise_for :admins

  devise_for :users
  
  resources :users

  get "home/index"
  

  root :to => 'home#index'
  

end

app/models/poll.rb
class Poll < ActiveRecord::Base
  attr_accessible :correo, :domicilio, :edad_cinco, :edad_cuatro, :edad_diez, :edad_dos, :edad_nueve, :edad_ocho, :edad_seis, :edad_siete, :edad_tres, :edad_tres, :edad_uno, :estudio, :materno, :nombre, :nombre_cinco, :nombre_cuatro, :nombre_diez, :nombre_dos, :nombre_nueve, :nombre_ocho, :nombre_seis, :nombre_siete, :nombre_tres, :nombre_uno, :paterno, :posicionamiento_a, :posicionamiento_b, :posicionamiento_c, :posicionamiento_d, :posicionamiento_e, :pregunta_a, :pregunta_observaciones, :profesion, :rol, :telefono, :tipo_cinco, :tipo_cuatro, :tipo_diez, :tipo_dos, :tipo_nueve, :tipo_ocho, :tipo_seis, :tipo_siete, :tipo_uno, :tipo_tres
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  
  def index
    @polls = Poll.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @polls }
    end
  end

  def show
    @poll = Poll.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @poll }
    end
  end

  def new
    @poll = Poll.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @poll }
    end
  end

  def edit
    @poll = Poll.find(params[:id])
  end

  def create
    @poll = Poll.new(params[:poll])

    respond_to do |format|
      if @poll.save

        format.html { redirect_to @poll }
#        format.html { redirect_to @general, notice: 'General was successfully created.' }
        
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @poll = Poll.find(params[:id])

    respond_to do |format|
      if @poll.update_attributes(params[:poll])
        format.html { redirect_to @poll, notice: 'La encuesta se actualizo correctamente' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @poll = Poll.find(params[:id])
    @poll.destroy

    respond_to do |format|
      format.html { redirect_to polls_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/polls/_form.html.erb
<%= form_for @poll, :html => { :class => 'form-inline' } do |f| %>
  <div class="control-group">
    <%= f.label :paterno, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :paterno, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :materno, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :materno, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :nombre, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nombre, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :telefono, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :telefono, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :correo, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :correo, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :domicilio, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :domicilio, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :estudio, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :estudio, [["Ninguna", "1"], ["Primaria", "2"], ["Segundaria", "3"], ["Prepa", "4"], ["Universidad", "5"],  ["Otro", "6"]  ], :class => 'number_field' %>


    </div>
  </div>
  <div class="control-group">
    <%= f.label :rol, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :rol, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :profesion, :class => 'control-label' %>
    <div class="controls"> 
      <%= f.text_field :profesion, :class => 'text_field' %>
    </div>
  </div>

<!-- ESTRUCTURA -->
<div class="page-header">
<h1>Estructura Familiar</h1>
</div>

<div class="control-group">
 1. Nombre
  <div class="controls">
    <%= f.text_field :nombre_uno, :class => 'text_field' %>
Tipo Familiar
	<%= f.select :tipo_uno, [["Ninguna", "1"], ["Padre", "2"], ["Madre", "3"], ["Hijo", "4"], ["Hija", "5"],  ["Abuela", "6"], ["Abuelo", "7"], ["Nieto", "8"],["Nieta", "9"],["Nuero", "10"], ["Nuera", "11"], ["Yerno", "12"], ["Sobrino", "13"], ["Sobrina", "14"],["Otro", "14"]], :class => 'number_field' %>
Edad
	<%= f.text_field :edad_uno, :class => 'text_field' %>
  </div>
</div>

<div class="control-group">
2. Nombre
  <div class="controls">
    <%= f.text_field :nombre_dos, :class => 'text_field' %>
Tipo Familiar
    <%= f.select :tipo_dos,[["Ninguna", "1"], ["Padre", "2"], ["Madre", "3"], ["Hijo", "4"], ["Hija", "5"],  ["Abuela", "6"], ["Abuelo", "7"], ["Nieto", "8"],["Nieta", "9"],["Nuero", "10"], ["Nuera", "11"], ["Yerno", "12"], ["Sobrino", "13"], ["Sobrina", "14"],["Otro", "14"]], :class => 'number_field' %>
Edad 
    <%= f.text_field :edad_dos, :class => 'text_field' %>
  </div>
</div>

<div class="control-group">
3. Nombre
  <div class="controls">
    <%= f.text_field :nombre_tres, :class => 'text_field' %>
Tipo Familiar
    <%= f.select :tipo_tres, [["Ninguna", "1"], ["Padre", "2"], ["Madre", "3"], ["Hijo", "4"], ["Hija", "5"],  ["Abuela", "6"], ["Abuelo", "7"], ["Nieto", "8"],["Nieta", "9"],["Nuero", "10"], ["Nuera", "11"], ["Yerno", "12"], ["Sobrino", "13"], ["Sobrina", "14"],["Otro", "14"]], :class => 'text_field' %>
Edad
    <%= f.text_field :edad_tres, :class => 'text_field' %>

  </div>
</div>

<div class="control-group">
4. Nombre
  <div class="controls">	
    <%= f.text_field :nombre_cuatro, :class => 'text_field' %>
Tipo Familiar
    <%= f.select :tipo_cuatro, [["Ninguna", "1"], ["Padre", "2"], ["Madre", "3"], ["Hijo", "4"], ["Hija", "5"],  ["Abuela", "6"], ["Abuelo", "7"], ["Nieto", "8"],["Nieta", "9"],["Nuero", "10"], ["Nuera", "11"], ["Yerno", "12"], ["Sobrino", "13"], ["Sobrina", "14"],["Otro", "14"]], :class => 'number_field' %>
Edad
    <%= f.text_field :edad_cuatro, :class => 'number_field' %>
  </div>
</div>



<div class="control-group">
5. Nombre
  <div class="controls">
    <%= f.text_field :nombre_cinco, :class => 'text_field' %>
Tipo Familiar
    <%= f.select :tipo_cinco, [["Ninguna", "1"], ["Padre", "2"], ["Madre", "3"], ["Hijo", "4"], ["Hija", "5"],  ["Abuela", "6"], ["Abuelo", "7"], ["Nieto", "8"],["Nieta", "9"],["Nuero", "10"], ["Nuera", "11"], ["Yerno", "12"], ["Sobrino", "13"], ["Sobrina", "14"],["Otro", "14"]], :class => 'number_field' %>
Edad
    <%= f.text_field :edad_cinco, :class => 'number_field' %>
  </div>
</div>

<div class="control-group">
6. Nombre
  <div class="controls">
    <%= f.text_field :nombre_seis, :class => 'text_field' %>
Tipo Familiar
    <%= f.select :tipo_seis, [["Ninguna", "1"], ["Padre", "2"], ["Madre", "3"], ["Hijo", "4"], ["Hija", "5"],  ["Abuela", "6"], ["Abuelo", "7"], ["Nieto", "8"],["Nieta", "9"],["Nuero", "10"], ["Nuera", "11"], ["Yerno", "12"], ["Sobrino", "13"], ["Sobrina", "14"],["Otro", "14"]], :class => 'number_field' %>
Edad
    <%= f.text_field :edad_seis, :class => 'number_field' %>
  </div>
</div>

<div class="control-group">
7. Nombre
  <div class="controls">
    <%= f.text_field :nombre_siete, :class => 'text_field' %>
Tipo Familiar
    <%= f.select :tipo_siete, [["Ninguna", "1"], ["Padre", "2"], ["Madre", "3"], ["Hijo", "4"], ["Hija", "5"],  ["Abuela", "6"], ["Abuelo", "7"], ["Nieto", "8"],["Nieta", "9"],["Nuero", "10"], ["Nuera", "11"], ["Yerno", "12"], ["Sobrino", "13"], ["Sobrina", "14"],["Otro", "14"]], :class => 'number_field' %>
Edad
    <%= f.text_field :edad_siete, :class => 'number_field' %>

  </div>
</div>

<div class="control-group">
8. Nombre
  <div class="controls">
    <%= f.text_field :nombre_ocho, :class => 'text_field' %>
Tipo Familiar
    <%= f.select :tipo_ocho, [["Ninguna", "1"], ["Padre", "2"], ["Madre", "3"], ["Hijo", "4"], ["Hija", "5"],  ["Abuela", "6"], ["Abuelo", "7"], ["Nieto", "8"],["Nieta", "9"],["Nuero", "10"], ["Nuera", "11"], ["Yerno", "12"], ["Sobrino", "13"], ["Sobrina", "14"],["Otro", "14"]], :class => 'number_field' %>
Edad
    <%= f.text_field :edad_ocho, :class => 'number_field' %>
  </div>
</div>

<div class="control-group">
9. Nombre
  <div class="controls">
    <%= f.text_field :nombre_nueve, :class => 'text_field' %>
Tipo Familiar
    <%= f.select :tipo_nueve,[["Ninguna", "1"], ["Padre", "2"], ["Madre", "3"], ["Hijo", "4"], ["Hija", "5"],  ["Abuela", "6"], ["Abuelo", "7"], ["Nieto", "8"],["Nieta", "9"],["Nuero", "10"], ["Nuera", "11"], ["Yerno", "12"], ["Sobrino", "13"], ["Sobrina", "14"],["Otro", "14"]], :class => 'text_field' %>
Edad
    <%= f.text_field :edad_nueve, :class => 'number_field' %>
  </div>
</div>

<div class="control-group">
10. Nombre
  <div class="controls">
    <%= f.text_field :nombre_diez, :class => 'text_field' %>
Tipo Familiar
	<%= f.select :tipo_diez, [["Ninguna", "1"], ["Padre", "2"], ["Madre", "3"], ["Hijo", "4"], ["Hija", "5"],  ["Abuela", "6"], ["Abuelo", "7"], ["Nieto", "8"],["Nieta", "9"],["Nuero", "10"], ["Nuera", "11"], ["Yerno", "12"], ["Sobrino", "13"], ["Sobrina", "14"],["Otro", "14"]],:class => 'number_field' %>
Edad	
	<%= f.text_field :edad_diez, :class => 'number_field' %>
  </div>
</div>

<!--- ENCUESTA -->

<div class="page-header">
<h1>Encuesta</h1>
</div>

<div class="control-group">
  <%= f.label "¿Conoce a los candidatos que quieren ser Gobernadores?", :class => 'control-label' %>
  <div class="controls">
    <%= f.check_box :posicionamiento_a, :class => 'check_box' %>
  </div>
</div>
<div class="control-group">
  <%= f.label "¿Conoce o ha oído de Miguel Márquez Márquez?", :class => 'control-label' %>
  <div class="controls">
    <%= f.check_box :posicionamiento_b, :class => 'check_box' %>
  </div>
</div>
<div class="control-group">
  <%= f.label "¿Usted está enterado de que Miguel Márquez Márquez aspira a ser Gobernador del Estado?", :class => 'control-label' %>
  <div class="controls">
    <%= f.check_box :posicionamiento_c, :class => 'check_box' %>
  </div>
</div>
<div class="control-group">
  <%= f.label "¿Conoce las propuestas de trabajo del Lic. Miguel Márquez Márquez?", :class => 'control-label' %>
  <div class="controls">
    <%= f.check_box :posicionamiento_d, :class => 'check_box' %>
  </div>
</div>
<div class="control-group">
  <%= f.label :posicionamiento_e, :class => 'control-label' %>
  <div class="controls">
    <%= f.check_box :posicionamiento_e, :class => 'check_box' %>
  </div>
</div>
<div class="control-group">
  <%= f.label "En tu opinión ¿esta persona votaría por Miguel Márquez Márquez?", :class => 'control-label' %>
  <div class="controls">
    <%= f.check_box :pregunta_a, :class => 'check_box' %>
  </div>
</div>
<div class="control-group">
  <%= f.label :pregunta_observaciones, :class => 'control-label' %>
  <div class="controls">
    <%= f.text_area :pregunta_observaciones, :class => 'text_area' %>
  </div>
</div>






  <div class="form-actions">
    <%= f.submit "Crear encuesta", :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                polls_path, :class => 'btn' %>
  </div>
<% end %>

app/views/polls/edit.html.erb
<%- model_class = @poll.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Editar encuesta") %></h1>
<%= render :partial => 'form' %>

app/views/polls/index.html.erb
<%- model_class = Poll.new.class -%>
<h1>Lista de Encuestas</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:paterno) %></th>
      <th><%= model_class.human_attribute_name(:materno) %></th>
      <th><%= model_class.human_attribute_name(:nombre) %></th>     
      <th>Creado a las</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @polls.each do |poll| %>
      <tr>
        <td><%= link_to poll.id, edit_poll_path(poll) %></td>
        <td><%= poll.paterno %></td>
        <td><%= poll.materno %></td>
        <td><%= poll.nombre %></td>
        <td><%= poll.telefono %></td>       
        <td>
          <%= link_to "Editar", edit_poll_path(poll), :class => 'btn btn-mini' %>
          <%= link_to "Eliminar",poll_path(poll),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Nuevo",
            new_poll_path,
            :class => 'btn btn-primary' %>

app/views/polls/new.html.erb
<%- model_class = @poll.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "Nueva Encuesta") %></h1>
<%= render :partial => 'form' %>

app/views/polls/show.html.erb
<%- model_class = @poll.class -%>
<h1>Ver Encuesta</h1>

<dl class="dl-horizontal">
<h3>Datos personales</h3>
  <dt><strong><%= model_class.human_attribute_name(:paterno) %>:</strong></dt>
  <dd><%= @poll.paterno %></dd>
  <dt><strong><%= model_class.human_attribute_name(:materno) %>:</strong></dt>
  <dd><%= @poll.materno %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nombre) %>:</strong></dt>
  <dd><%= @poll.nombre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:telefono) %>:</strong></dt>
  <dd><%= @poll.telefono %></dd>
  <dt><strong><%= model_class.human_attribute_name(:correo) %>:</strong></dt>
  <dd><%= @poll.correo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:domicilio) %>:</strong></dt>
  <dd><%= @poll.domicilio %></dd>
  <dt><strong><%= model_class.human_attribute_name(:estudio) %>:</strong></dt>
  <dd><%= @poll.estudio %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rol) %>:</strong></dt>
  <dd><%= @poll.rol %></dd>
  <dt><strong><%= model_class.human_attribute_name(:profesion) %>:</strong></dt>
  <dd><%= @poll.profesion %></dd>
<h3>Estructura Familiar</h3>
  <dt><strong>1. Nombre:</strong></dt>
  <dd><%= @poll.nombre_uno %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tipo_uno) %>:<%= @poll.tipo_uno %></strong></dt>
  <dd><%= @poll.tipo_uno %></dd>
  <dt><strong><%= model_class.human_attribute_name(:edad_uno) %>:</strong></dt>
  <dd><%= @poll.edad_uno %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nombre_dos) %>:</strong></dt>
  <dd><%= @poll.nombre_dos %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tipo_dos) %>:</strong></dt>
  <dd><%= @poll.tipo_dos %></dd>
  <dt><strong><%= model_class.human_attribute_name(:edad_dos) %>:</strong></dt>
  <dd><%= @poll.edad_dos %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nombre_tres) %>:</strong></dt>
  <dd><%= @poll.nombre_tres %></dd>
  <dt><strong><%= model_class.human_attribute_name(:edad_tres) %>:</strong></dt>
  <dd><%= @poll.edad_tres %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nombre_cuatro) %>:</strong></dt>
  <dd><%= @poll.nombre_cuatro %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tipo_cuatro) %>:</strong></dt>
  <dd><%= @poll.tipo_cuatro %></dd>
  <dt><strong><%= model_class.human_attribute_name(:edad_cuatro) %>:</strong></dt>
  <dd><%= @poll.edad_cuatro %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nombre_cinco) %>:</strong></dt>
  <dd><%= @poll.nombre_cinco %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tipo_cinco) %>:</strong></dt>
  <dd><%= @poll.tipo_cinco %></dd>
  <dt><strong><%= model_class.human_attribute_name(:edad_cinco) %>:</strong></dt>
  <dd><%= @poll.edad_cinco %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nombre_seis) %>:</strong></dt>
  <dd><%= @poll.nombre_seis %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tipo_seis) %>:</strong></dt>
  <dd><%= @poll.tipo_seis %></dd>
  <dt><strong><%= model_class.human_attribute_name(:edad_seis) %>:</strong></dt>
  <dd><%= @poll.edad_seis %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nombre_siete) %>:</strong></dt>
  <dd><%= @poll.nombre_siete %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tipo_siete) %>:</strong></dt>
  <dd><%= @poll.tipo_siete %></dd>
  <dt><strong><%= model_class.human_attribute_name(:edad_siete) %>:</strong></dt>
  <dd><%= @poll.edad_siete %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nombre_ocho) %>:</strong></dt>
  <dd><%= @poll.nombre_ocho %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tipo_ocho) %>:</strong></dt>
  <dd><%= @poll.tipo_ocho %></dd>
  <dt><strong><%= model_class.human_attribute_name(:edad_ocho) %>:</strong></dt>
  <dd><%= @poll.edad_ocho %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nombre_nueve) %>:</strong></dt>
  <dd><%= @poll.nombre_nueve %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tipo_nueve) %>:</strong></dt>
  <dd><%= @poll.tipo_nueve %></dd>
  <dt><strong><%= model_class.human_attribute_name(:edad_nueve) %>:</strong></dt>
  <dd><%= @poll.edad_nueve %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nombre_diez) %>:</strong></dt>
  <dd><%= @poll.nombre_diez %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tipo_diez) %>:</strong></dt>
  <dd><%= @poll.tipo_diez %></dd>
  <dt><strong><%= model_class.human_attribute_name(:edad_diez) %>:</strong></dt>
  <dd><%= @poll.edad_diez %></dd>
<h3>Encuesta</h3>
  <dt><strong><%= model_class.human_attribute_name(:posicionamiento_a) %>:</strong></dt>
  <dd><%= @poll.posicionamiento_a %></dd>
  <dt><strong><%= model_class.human_attribute_name(:posicionamiento_b) %>:</strong></dt>
  <dd><%= @poll.posicionamiento_b %></dd>
  <dt><strong><%= model_class.human_attribute_name(:posicionamiento_c) %>:</strong></dt>
  <dd><%= @poll.posicionamiento_c %></dd>
  <dt><strong><%= model_class.human_attribute_name(:posicionamiento_d) %>:</strong></dt>
  <dd><%= @poll.posicionamiento_d %></dd>
  <dt><strong><%= model_class.human_attribute_name(:posicionamiento_e) %>:</strong></dt>
  <dd><%= @poll.posicionamiento_e %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pregunta_a) %>:</strong></dt>
  <dd><%= @poll.pregunta_a %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pregunta_observaciones) %>:</strong></dt>
  <dd><%= @poll.pregunta_observaciones %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              polls_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_poll_path(@poll), :class => 'btn' %>
  <%= link_to t("'.destroy'", :default => t("helpers.links.destroy")),
              poll_path(@poll),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>