config/routes.rb
Encuentas::Application.routes.draw do

  resources :bunkers

  resources :incidences

  resources :boxes

  resources :polls
  resources :familystructures
  resources :generals
  resources :poll_steps
  devise_for :admins

  devise_for :users
  
  resources :users

  get "home/index"
  

  root :to => 'home#index'
  

end

app/models/familystructure.rb
class Familystructure < ActiveRecord::Base
  attr_accessible :edad, :id_general, :materno, :nombre, :parentesco, :paterno
end

app/controllers/familystructures_controller.rb
class FamilystructuresController < ApplicationController
  # GET /familystructures
  # GET /familystructures.json
  def index
    @familystructures = Familystructure.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @familystructures }
    end
  end

  # GET /familystructures/1
  # GET /familystructures/1.json
  def show
    @familystructure = Familystructure.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @familystructure }
    end
  end

  # GET /familystructures/new
  # GET /familystructures/new.json
  def new
    @familystructure = Familystructure.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @familystructure }
    end
  end

  # GET /familystructures/1/edit
  def edit
    @familystructure = Familystructure.find(params[:id])
  end

  # POST /familystructures
  # POST /familystructures.json
  def create
    @familystructure = Familystructure.new(params[:familystructure])

    respond_to do |format|
      if @familystructure.save
        format.html { redirect_to @familystructure, notice: 'Familystructure was successfully created.' }
        format.json { render json: @familystructure, status: :created, location: @familystructure }
      else
        format.html { render action: "new" }
        format.json { render json: @familystructure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /familystructures/1
  # PUT /familystructures/1.json
  def update
    @familystructure = Familystructure.find(params[:id])

    respond_to do |format|
      if @familystructure.update_attributes(params[:familystructure])
        format.html { redirect_to @familystructure, notice: 'Familystructure was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @familystructure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /familystructures/1
  # DELETE /familystructures/1.json
  def destroy
    @familystructure = Familystructure.find(params[:id])
    @familystructure.destroy

    respond_to do |format|
      format.html { redirect_to familystructures_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/familystructures_helper.rb
module FamilystructuresHelper
end

app/views/familystructures/_form.html.erb
<%= form_for(@familystructure) do |f| %>
  <% if @familystructure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@familystructure.errors.count, "error") %> prohibited this familystructure from being saved:</h2>

      <ul>
      <% @familystructure.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :paterno %><br />
    <%= f.text_field :paterno %>
  </div>
  <div class="field">
    <%= f.label :materno %><br />
    <%= f.text_field :materno %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :parentesco %><br />
    <%= f.text_field :parentesco %>
  </div>
  <div class="field">
    <%= f.label :edad %><br />
    <%= f.number_field :edad %>
  </div>
  <div class="field">
    <%= f.label :id_general %><br />
    <%= f.number_field :id_general %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/familystructures/edit.html.erb
<h1>Editing familystructure</h1>

<%= render 'form' %>

<%= link_to 'Show', @familystructure %> |
<%= link_to 'Back', familystructures_path %>

app/views/familystructures/index.html.erb
<h1>Listing familystructures</h1>

<table>
  <tr>
    <th>Paterno</th>
    <th>Materno</th>
    <th>Nombre</th>
    <th>Parentesco</th>
    <th>Edad</th>
    <th>Id general</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @familystructures.each do |familystructure| %>
  <tr>
    <td><%= familystructure.paterno %></td>
    <td><%= familystructure.materno %></td>
    <td><%= familystructure.nombre %></td>
    <td><%= familystructure.parentesco %></td>
    <td><%= familystructure.edad %></td>
    <td><%= familystructure.id_general %></td>
    <td><%= link_to 'Show', familystructure %></td>
    <td><%= link_to 'Edit', edit_familystructure_path(familystructure) %></td>
    <td><%= link_to 'Destroy', familystructure, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Familystructure', new_familystructure_path %>

app/views/familystructures/new.html.erb
<h1>New familystructure</h1>

<%= render 'form' %>

<%= link_to 'Back', familystructures_path %>

app/views/familystructures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Paterno:</b>
  <%= @familystructure.paterno %>
</p>

<p>
  <b>Materno:</b>
  <%= @familystructure.materno %>
</p>

<p>
  <b>Nombre:</b>
  <%= @familystructure.nombre %>
</p>

<p>
  <b>Parentesco:</b>
  <%= @familystructure.parentesco %>
</p>

<p>
  <b>Edad:</b>
  <%= @familystructure.edad %>
</p>

<p>
  <b>Id general:</b>
  <%= @familystructure.id_general %>
</p>


<%= link_to 'Edit', edit_familystructure_path(@familystructure) %> |
<%= link_to 'Back', familystructures_path %>